### ISSUE TITLE
segment fault when use staff -F option

### ISSUE THREAD

**Issue by starnight0** [aquaskyline/SOAPdenovo2#11]
Hello,

I got "Segmentation fault" when I run SOAPdenovo2-127mer scaff with -F option, but don't have the problem when run without '-F'. Could you fix the problem?

STDERR is:

********************
Scaff
********************

Parameters: scaff -g K127.d1.e0.M0.G100.b2.V.F -G 100 -b 2 -V -N 1500000000 -p 8 -F -S 

Files for scaffold construction are OK.

There are 1 grad(s), 238087400 read(s), max read len 1000.
Kmer size: 127
There are 5997196 edge(s) in edge file.
Mask contigs with coverage lower than 1.0 or higher than 20.0, and strict length 0.
Average contig coverage is 10, 1351551 contig(s) masked.
Mask contigs shorter than 129, 1143042 contig(s) masked.
6685784 arc(s) loaded, average weight is 6.
2998621 contig(s) loaded.
Done loading updated edges.
Time spent on loading updated edges: 136s.

Start to load reads for gap filling. 100 length discrepancy is allowed.
...
Loaded 56747993 reads from K127.d1.e0.M0.G100.b2.V.F.readInGap.
8 thread(s) initialized.
1000 scaffolds processed.
2000 scaffolds processed.
3000 scaffolds processed.
4000 scaffolds processed.
5000 scaffolds processed.
6000 scaffolds processed.
7000 scaffolds processed.
8000 scaffolds processed.
9000 scaffolds processed.
10000 scaffolds processed.
/opt/gridengine/default/Federation/spool/execd/kcompute83/job_scripts/1118308: line 83: 
 8077 Segmentation fault      (core dumped) ~/bin/SOAPdenovo-127mer scaff -g K127.d1.e0.
M0.G100.b2.V.F -G 100 -b 2 -V -N 1500000000 -p 8 -F -S

Thanks,
Zelin

**Comment by aquaskyline** [comment]
try if you can finish the scaff step with -F parameter only.
