### ISSUE TITLE
The header in SOAPdenovo output ?

### ISSUE THREAD

**Issue by ptranvan** [aquaskyline/SOAPdenovo2#13]
Hi,

My output from the assembler is formatted like this

> scaffold148     17.4
> scaffold149     37.1

What is that second number ? Is it the coverage ? If yes I don't understand what it means in an assembly.

I mean the coverage is normally the number of time that a base is represented/sequenced. What does it mean in that case ??

**Comment by aquaskyline** [comment]
It's the average kmer frequency for all kmers that comprise the scaffold.

**Comment by ptranvan** [comment]
Hi, 

Is it the same than scaffold coverage ?

**Comment by aquaskyline** [comment]
Yes
