### ISSUE TITLE
glibc detected error on cluster

### ISSUE THREAD

**Issue by andreyurch** [aquaskyline/SOAPdenovo2#14]
Hello, 
 I've got this error during the execution of SopaDenovo2 on the computer cluster

Version 2.04: released on July 13th, 2012
Compile Aug 18 2016	15:47:18
all: invalid option -- 'n'

********************
Pregraph
********************

Parameters: pregraph -s /export/home/aay2c/soapdenovo_assembly/soap.config.sh -K 61 -p 64 -d 2 -R -o Soap_only_Pe 

In /export/home/aay2c/soapdenovo_assembly/soap.config.sh, 1 lib(s), maximum read length 150, maximum name length 256.

64 thread(s) initialized.
Import reads from file:
 /export/home/aay2c/zootoca_quorum/quorum_corrected_1.fa
--- 100000000th reads.
--- 200000000th reads.
--- 300000000th reads.
Time spent on hashing reads: 2386s, 343108542 read(s) processed.
LIB(s) information:
 [LIB] 0, avg_ins 300, reverse 0.
1624289639 node(s) allocated, 27102103123 kmer(s) in reads, 27102103123 kmer(s) processed.
*** glibc detected *** /export/home/aay2c/app/soapdenovo_source/SOAPdenovo-63mer: double free or corruption (out): 0x0000000002238140 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3aee675f4e]
/lib64/libc.so.6[0x3aee678cf0]
/export/home/aay2c/app/soapdenovo_source/SOAPdenovo-63mer[0x4506d4]
/export/home/aay2c/app/soapdenovo_source/SOAPdenovo-63mer[0x44e01e]
/export/home/aay2c/app/soapdenovo_source/SOAPdenovo-63mer[0x436dc9]
/export/home/aay2c/app/soapdenovo_source/SOAPdenovo-63mer[0x437c0e]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3aee61ed5d]
/export/home/aay2c/app/soapdenovo_source/SOAPdenovo-63mer[0x4047d9]
======= Memory map: ========
00400000-0048d000 r-xp 00000000 00:14 13320720085852621861               /export/home/aay2c/app/soapdenovo_source/SOAPdenovo-63mer
0068d000-0068e000 rw-p 0008d000 00:14 13320720085852621861               /export/home/aay2c/app/soapdenovo_source/SOAPdenovo-63mer
0068e000-0080e000 rw-p 00000000 00:00 0 
02238000-0cbfd000 rw-p 00000000 00:00 0                                  [heap]
3aee200000-3aee220000 r-xp 00000000 09:01 262150                         /lib64/ld-2.12.so
3aee41f000-3aee420000 r--p 0001f000 09:01 262150                         /lib64/ld-2.12.so
3aee420000-3aee421000 rw-p 00020000 09:01 262150                         /lib64/ld-2.12.so
3aee421000-3aee422000 rw-p 00000000 00:00 0 
3aee600000-3aee78a000 r-xp 00000000 09:01 262151                         /lib64/libc-2.12.so
3aee78a000-3aee98a000 ---p 0018a000 09:01 262151                         /lib64/libc-2.12.so
3aee98a000-3aee98e000 r--p 0018a000 09:01 262151                         /lib64/libc-2.12.so
3aee98e000-3aee98f000 rw-p 0018e000 09:01 262151                         /lib64/libc-2.12.so
3aee98f000-3aee994000 rw-p 00000000 00:00 0 
3aeea00000-3aeea83000 r-xp 00000000 09:01 262163                         /lib64/libm-2.12.so
3aeea83000-3aeec82000 ---p 00083000 09:01 262163                         /lib64/libm-2.12.so
3aeec82000-3aeec83000 r--p 00082000 09:01 262163                         /lib64/libm-2.12.so
3aeec83000-3aeec84000 rw-p 00083000 09:01 262163                         /lib64/libm-2.12.so
3aeee00000-3aeee17000 r-xp 00000000 09:01 262158                         /lib64/libpthread-2.12.so
3aeee17000-3aef017000 ---p 00017000 09:01 262158                         /lib64/libpthread-2.12.so
3aef017000-3aef018000 r--p 00017000 09:01 262158                         /lib64/libpthread-2.12.so
3aef018000-3aef019000 rw-p 00018000 09:01 262158                         /lib64/libpthread-2.12.so
3aef019000-3aef01d000 rw-p 00000000 00:00 0 
3aef600000-3aef615000 r-xp 00000000 09:01 262172                         /lib64/libz.so.1.2.3
3aef615000-3aef814000 ---p 00015000 09:01 262172                         /lib64/libz.so.1.2.3
3aef814000-3aef815000 r--p 00014000 09:01 262172                         /lib64/libz.so.1.2.3
3aef815000-3aef816000 rw-p 00015000 09:01 262172                         /lib64/libz.so.1.2.3
3aefa00000-3aefa07000 r-xp 00000000 09:01 262166                         /lib64/librt-2.12.so
3aefa07000-3aefc06000 ---p 00007000 09:01 262166                         /lib64/librt-2.12.so
3aefc06000-3aefc07000 r--p 00006000 09:01 262166                         /lib64/librt-2.12.so
3aefc07000-3aefc08000 rw-p 00007000 09:01 262166                         /lib64/librt-2.12.so
3aefe00000-3aefe16000 r-xp 00000000 09:01 262182                         /lib64/libgcc_s-4.4.7-20120601.so.1
3aefe16000-3af0015000 ---p 00016000 09:01 262182                         /lib64/libgcc_s-4.4.7-20120601.so.1
3af0015000-3af0016000 rw-p 00015000 09:01 262182                         /lib64/libgcc_s-4.4.7-20120601.so.1
3af0a00000-3af0ae8000 r-xp 00000000 09:01 3410130                        /usr/lib64/libstdc++.so.6.0.13
3af0ae8000-3af0ce8000 ---p 000e8000 09:01 3410130                        /usr/lib64/libstdc++.so.6.0.13
3af0ce8000-3af0cef000 r--p 000e8000 09:01 3410130                        /usr/lib64/libstdc++.so.6.0.13
3af0cef000-3af0cf1000 rw-p 000ef000 09:01 3410130                        /usr/lib64/libstdc++.so.6.0.13
3af0cf1000-3af0d06000 rw-p 00000000 00:00 0 
7f03d8000000-7f03d8021000 rw-p 00000000 00:00 0 
7f03d8021000-7f03dc000000 ---p 00000000 00:00 0 
7f03de360000-7f03de361000 rw-p 00000000 00:00 0 
7f03de361000-7f03de362000 ---p 00000000 00:00 0 
7f03de362000-7f03de365000 rw-p 00000000 00:00 0 
7f03de365000-7f03de366000 ---p 00000000 00:00 0 
7f03de366000-7f03ded66000 rw-p 00000000 00:00 0 
7f03ded66000-7f03ded67000 ---p 00000000 00:00 0 
7f03ded67000-7f03df767000 rw-p 00000000 00:00 0 
7f03df767000-7f03df768000 ---p 00000000 00:00 0 
7f03df768000-7f03e0168000 rw-p 00000000 00:00 0 
7f03e0168000-7f03e0169000 ---p 00000000 00:00 0 
7f03e0169000-7f03e0b69000 rw-p 00000000 00:00 0 
7f03e0b69000-7f03e0b6a000 ---p 00000000 00:00 0 
7f03e0b6a000-7f03e156a000 rw-p 00000000 00:00 0 
7f03e156a000-7f03e156b000 ---p 00000000 00:00 0 
7f03e156b000-7f03e1f6b000 rw-p 00000000 00:00 0 
7f03e1f6b000-7f03e1f6c000 ---p 00000000 00:00 0 
7f03e1f6c000-7f03e296c000 rw-p 00000000 00:00 0 
7f03e296c000-7f03e296d000 ---p 00000000 00:00 0 
7f03e296d000-7f03e336d000 rw-p 00000000 00:00 0 
7f03e336d000-7f03e336e000 ---p 00000000 00:00 0 
7f03e336e000-7f03e3d6e000 rw-p 00000000 00:00 0 
7f03e3d6e000-7f03e3d6f000 ---p 00000000 00:00 0 
7f03e3d6f000-7f03e476f000 rw-p 00000000 00:00 0 
7f03e476f000-7f03e4770000 ---p 00000000 00:00 0 
7f03e4770000-7f03e5170000 rw-p 00000000 00:00 0 
7f03e5170000-7f03e5171000 ---p 00000000 00:00 0 
7f03e5171000-7f03e5b71000 rw-p 00000000 00:00 0 
7f03e5b71000-7f03e5b72000 ---p 00000000 00:00 0 
7f03e5b72000-7f03e6572000 rw-p 00000000 00:00 0 
7f03e6572000-7f03e6573000 ---p 00000000 00:00 0 
7f03e6573000-7f03e6f73000 rw-p 00000000 00:00 0 
7f03e6f73000-7f03e6f74000 ---p 00000000 00:00 0 
7f03e6f74000-7f03e7974000 rw-p 00000000 00:00 0 
7f03e7974000-7f03e7975000 ---p 00000000 00:00 0 
7f03e7975000-7f03e8375000 rw-p 00000000 00:00 0 
7f03e8375000-7f03e8376000 ---p 00000000 00:00 0 
7f03e8376000-7f03e8d76000 rw-p 00000000 00:00 0 
7f03e8d76000-7f03e8d77000 ---p 00000000 00:00 0 
7f03e8d77000-7f03e9777000 rw-p 00000000 00:00 0 
7f03e9777000-7f03e9778000 ---p 00000000 00:00 0 
7f03e9778000-7f03ea178000 rw-p 00000000 00:00 0 
7f03ea178000-7f03ea179000 ---p 00000000 00:00 0 
7f03ea179000-7f03eab79000 rw-p 00000000 00:00 0 
7f03eab79000-7f03eab7a000 ---p 00000000 00:00 0 
7f03eab7a000-7f03eb57a000 rw-p 00000000 00:00 0 
7f03eb57a000-7f03eb57b000 ---p 00000000 00:00 0 
7f03eb57b000-7f03ebf7b000 rw-p 00000000 00:00 0 
7f03ebf7b000-7f03ebf7c000 ---p 00000000 00:00 0 
7f03ebf7c000-7f03ec97c000 rw-p 00000000 00:00 0 
7f03ec97c000-7f03ec97d000 ---p 00000000 00:00 0 
7f03ec97d000-7f03ed37d000 rw-p 00000000 00:00 0 
7f03ed37d000-7f03ed37e000 ---p 00000000 00:00 0 
7f03ed37e000-7f03edd7e000 rw-p 00000000 00:00 0 
7f03edd7e000-7f03edd7f000 ---p 00000000 00:00 0 
7f03edd7f000-7f03ee77f000 rw-p 00000000 00:00 0 
7f03ee77f000-7f03ee780000 ---p 00000000 00:00 0 
7f03ee780000-7f03ef180000 rw-p 00000000 00:00 0 
7f03ef180000-7f03ef181000 ---p 00000000 00:00 0 
7f03ef181000-7f03efb81000 rw-p 00000000 00:00 0 
7f03efb81000-7f03efb82000 ---p 00000000 00:00 0 
7f03efb82000-7f03f0582000 rw-p 00000000 00:00 0 
7f03f0582000-7f03f0583000 ---p 00000000 00:00 0 
7f03f0583000-7f03f0f83000 rw-p 00000000 00:00 0 
7f03f0f83000-7f03f0f84000 ---p 00000000 00:00 0 
7f03f0f84000-7f03f1984000 rw-p 00000000 00:00 0 
7f03f1984000-7f03f1985000 ---p 00000000 00:00 0 
7f03f1985000-7f03f2385000 rw-p 00000000 00:00 0 
7f03f2385000-7f03f2386000 ---p 00000000 00:00 0 
7f03f2386000-7f03f2d86000 rw-p 00000000 00:00 0 
7f03f2d86000-7f03f2d87000 ---p 00000000 00:00 0 
7f03f2d87000-7f03f3787000 rw-p 00000000 00:00 0 
7f03f3787000-7f03f3788000 ---p 00000000 00:00 0 
7f03f3788000-7f03f4188000 rw-p 00000000 00:00 0 
7f03f4188000-7f03f4189000 ---p 00000000 00:00 0 
7f03f4189000-7f03f4b89000 rw-p 00000000 00:00 0 
7f03f4b89000-7f03f4b8a000 ---p 00000000 00:00 0 
7f03f4b8a000-7f03f558a000 rw-p 00000000 00:00 0 
7f03f558a000-7f03f558b000 ---p 00000000 00:00 0 
7f03f558b000-7f03f5f8b000 rw-p 00000000 00:00 0 
7f03f5f8b000-7f03f5f8c000 ---p 00000000 00:00 0 
7f03f5f8c000-7f03f698c000 rw-p 00000000 00:00 0 
7f03f698c000-7f03f698d000 ---p 00000000 00:00 0 
7f03f698d000-7f03f738d000 rw-p 00000000 00:00 0 
7f03f738d000-7f03f738e000 ---p 00000000 00:00 0 
7f03f738e000-7f03f7d8e000 rw-p 00000000 00:00 0 
7f03f7d8e000-7f03f7d8f000 ---p 00000000 00:00 0 
7f03f7d8f000-7f03f878f000 rw-p 00000000 00:00 0 
7f03f878f000-7f03f8790000 ---p 00000000 00:00 0 
7f03f8790000-7f03f9190000 rw-p 00000000 00:00 0 
7f03f9190000-7f03f9191000 ---p 00000000 00:00 0 
7f03f9191000-7f03f9b91000 rw-p 00000000 00:00 0 
7f03f9b91000-7f03f9b92000 ---p 00000000 00:00 0 
7f03f9b92000-7f03fa592000 rw-p 00000000 00:00 0 
7f03fa592000-7f03fa593000 ---p 00000000 00:00 0 
7f03fa593000-7f03faf93000 rw-p 00000000 00:00 0 
7f03faf93000-7f03faf94000 ---p 00000000 00:00 0 
7f03faf94000-7f03fb994000 rw-p 00000000 00:00 0 
7f03fb994000-7f03fb995000 ---p 00000000 00:00 0 
7f03fb995000-7f03fc395000 rw-p 00000000 00:00 0 
7f03fc395000-7f03fc396000 ---p 00000000 00:00 0 
7f03fc396000-7f03fcd96000 rw-p 00000000 00:00 0 
7f03fcd96000-7f03fcd97000 ---p 00000000 00:00 0 
7f03fcd97000-7f03fd797000 rw-p 00000000 00:00 0 
7f03fd797000-7f03fd798000 ---p 00000000 00:00 0 
7f03fd798000-7f03fe198000 rw-p 00000000 00:00 0 
7f03fe198000-7f03fe199000 ---p 00000000 00:00 0 
7f03fe199000-7f03feb99000 rw-p 00000000 00:00 0 
7f03feb99000-7f03feb9a000 ---p 00000000 00:00 0 
7f03feb9a000-7f03ff59a000 rw-p 00000000 00:00 0 
7f03ff59a000-7f03ff59b000 ---p 00000000 00:00 0 
7f03ff59b000-7f03fff9b000 rw-p 00000000 00:00 0 
7f03fff9b000-7f03fff9c000 ---p 00000000 00:00 0 
7f03fff9c000-7f040099c000 rw-p 00000000 00:00 0 
7f040099c000-7f040099d000 ---p 00000000 00:00 0 
7f040099d000-7f040139d000 rw-p 00000000 00:00 0 
7f040139d000-7f040139e000 ---p 00000000 00:00 0 
7f040139e000-7f0401d9e000 rw-p 00000000 00:00 0 
7f0401d9e000-7f0401d9f000 ---p 00000000 00:00 0 
7f0401d9f000-7f040279f000 rw-p 00000000 00:00 0 
7f040279f000-7f04027a0000 ---p 00000000 00:00 0 
7f04027a0000-7f04031a0000 rw-p 00000000 00:00 0 
7f04031a0000-7f04031a1000 ---p 00000000 00:00 0 
7f04031a1000-7f0403ba1000 rw-p 00000000 00:00 0 
7f0403ba1000-7f0403ba2000 ---p 00000000 00:00 0 
7f0403ba2000-7f04045a2000 rw-p 00000000 00:00 0 
7f04045a2000-7f04045a3000 ---p 00000000 00:00 0 
7f04045a3000-7f0404fa3000 rw-p 00000000 00:00 0 
7f0404fa3000-7f0404fa4000 ---p 00000000 00:00 0 
7f0404fa4000-7f04059a4000 rw-p 00000000 00:00 0 
7f04059a4000-7f04059a5000 ---p 00000000 00:00 0 
7f04059a5000-7f10c24b3000 rw-p 00000000 00:00 0 
7f10c24d0000-7f10c24d1000 rw-p 00000000 00:00 0 
7ffe3ea74000-7ffe3ea89000 rw-p 00000000 00:00 0                          [stack]
7ffe3eba3000-7ffe3eba4000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
/var/spool/torque/mom_priv/jobs/313089.headnode03.cent.gla.ac.uk.SC: line 6: 23720 Aborted

**Comment by aquaskyline** [comment]
troubleshooting this problem needs a lot of details of your server, but changing a server with a different version of operating system can solve the problem.
