### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by tillea** [aquaskyline/SOAPdenovo2#16]
Hi,
you might probably know that soapdenovo2 is distributed by Debian.  The Debian Med team is maintaining the package inside Debian and it would help to simplify our work if you could add version tags to your releases since we will be automatically informed if new releases will be available.
Kind regards, Andreas.

**Comment by aquaskyline** [comment]
Thanks Andreas. Tag added.

**Comment by tillea** [comment]
On Fri, Dec 02, 2016 at 08:18:14PM -0800, aquaskyline wrote:
> Thanks Andreas. Tag added.
Thanks for the quick response.  Debian package will be updated accordingly.

-- 
http://fam-tille.de
