### ISSUE TITLE
version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by aersoares81** [aquaskyline/SOAPdenovo2#22]
Hi, apparently the binaries compiled with no error, but I'm getting these erros I've never seen with previous versions:
```
/home/user/bin/SOAPdenovo-63mer: /usr/local/gcc-4.8.1/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/user/bin/SOAPdenovo-63mer)
/home/user/bin/SOAPdenovo-63mer: /usr/local/gcc-4.8.1/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/user/bin/SOAPdenovo-63mer)
/home/user/bin/SOAPdenovo-63mer: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/user/bin/SOAPdenovo-63mer)
```

**Comment by aquaskyline** [comment]
This is because the libraries of the gcc version 4.8.1 you were using where not reachable by the paths you've defined in an environment variable $LD_LIBRARY_PATH. I suggest you to use bioconda to install SOAPdenovo.
