### ISSUE TITLE
finalFusion: not enough memory error (but enough is available)

### ISSUE THREAD

**Issue by quokkamole** [aquaskyline/SOAPdenovo2#23]
I'm trying to use finalFusion to prepare some contigs for scaffolding. I can get everything to work fine on my local machine but I'm encountering problems when attempting this on a cluster (with Torque scheduler) with the same amount of available memory (12GB for a small test data file with only 327 sequences). BTW there's a typo in the error message ('enought').

finalFusion compiles with no problems. Here's the output from stdout:

```
/finalFusion -K 33 -D -c /input/output.fa -g /output/soap
Mapping & Scaffolding module.
[main]Data prepare mode selected .
not enought memory
```

Requested resources on the cluster are as follows:
`Resources: mem=12000mb,neednodes=1:ppn=2:intel,nodes=1:ppn=2:intel,vmem=12000mb,walltime=00:30:00
`
Resources used on the cluster are as follows:
`ResourcesUsed:      cput=00:00:00,energy_used=0,mem=0kb,vmem=0kb,walltime=00:00:17`

Output from free -m and vmstat -s immediately prior to execution are as follows:

```
free -m
             total       used       free     shared    buffers     cached
Mem:        120984      94769      26214          0        106      86892
-/+ buffers/cache:       7770     113213
Swap:            0          0          0
vmstat -s
    123888000  total memory
     97044368  used memory
     64228880  active memory
     31563736  inactive memory
     26843632  free memory
       109368  buffer memory
     88977984  swap cache
            0  total swap
            0  used swap
            0  free swap
   9208005092 non-nice user cpu ticks
         8779 nice user cpu ticks
    367979891 system cpu ticks
   4830637734 idle cpu ticks
     21968833 IO-wait cpu ticks
        37217 IRQ cpu ticks
      5125532 softirq cpu ticks
       669352 stolen cpu ticks
     91741034 pages paged in
   1724763415 pages paged out
            0 pages swapped in
            0 pages swapped out
   2558299138 interrupts
   2576345523 CPU context switches
   1481842300 boot time
     79999921 forks
```

Any ideas? I'm a bit stumped.

**Comment by aquaskyline** [comment]
Please change line 64 in the fusion/prepare.c file from
IO_CTG *pre_ctg = (IO_CTG *)ckalloc(1000000000 * sizeof(IO_CTG));
to
IO_CTG *pre_ctg = (IO_CTG *)ckalloc(100000000 * sizeof(IO_CTG));
then compile and try again.

Typo fixed.
