### ISSUE TITLE
for  SOAPdenovo-fusion

### ISSUE THREAD

**Issue by SiyuanZhangB** [aquaskyline/SOAPdenovo2#25]
if I have a single reads. so, its means that i only use for MEGAHIT, cant use SOAPdenovo-fusion and SOAPdenovo for map and scaff ?

**Comment by aquaskyline** [comment]
Paired-end reads are required for scaffolding.

**Comment by SiyuanZhangB** [comment]
OK.  I am very glad for your reversion! thanks for  give me your advice. so, it means that my single-reads do assembly can only use for MEGAHIT.
