### ISSUE TITLE
How to use SOAPdenovo-fusion scaffold the output of MEGAHIT?

### ISSUE THREAD

**Issue by YiweiNiu** [aquaskyline/SOAPdenovo2#26]
Hi,
I'm using MEGAHIT for genome assembly of an insect (~800Mbp), and I found that the manual of SOAPdenovo2 mentioned that SOAPdenovo-fusion can be used to scaffold the contigs produced by MEGAHIT. But there are few documents about how to do it, such as how can I choose K-mer for SOAPdenovo-fusion? 
Any suggestions or thoughts would be appreciated.

Best,
Yiwei Niu

**Comment by aquaskyline** [comment]
A rule of thumb would be using half of your read length as kmer size.

**Comment by YiweiNiu** [comment]
Thank you for your quick reply!
But when I use SOAPdenovo-fusion like this:
`SOAPdenovo-fusion -D -K 75 -c megahit_out/final.contigs.fa`
I got the following error message:
```
Mapping & Scaffolding module.
[main]Data prepare mode selected .
All contigs loaded.
sh: -c: line 0: syntax error near unexpected token `null'
sh: -c: line 0: `touch (null).Arc'
```
Thanks again!

**Comment by aquaskyline** [comment]
Please also use -g
SOAPdenovo-fusion -D -K 75 -c megahit_out/final.contigs.fa -g somePrefix

Please try start with a smaller kmer size, say 41.

**Comment by YiweiNiu** [comment]
Thanks! It works. The read length in my case is PE151, shoudn't I use 75-mer (half of the read length, as you mentioned above)?

**Comment by aquaskyline** [comment]
there is no "should", start with 1/3 and increase to 1/2

**Comment by YiweiNiu** [comment]
Thanks a lot!

**Comment by ThymeLy** [comment]
Hi, 
can I know what it means by some_prefix as in (-g Prefix of input files)? 
As I only have one input file, which is the assembled contigs .fa file and want to use SOAPdenovo-fusion to scaffold it.

> Please also use -g
> SOAPdenovo-fusion -D -K 75 -c megahit_out/final.contigs.fa -g somePrefix
> 
> Please try start with a smaller kmer size, say 41.

**Comment by phylobase-web** [comment]
Have you checked readme.md?

https://github.com/aquaskyline/SOAPdenovo2/blob/master/README.md

2019年6月11日(火) 11:08 ThymeLy <notifications@github.com>:
