### ISSUE TITLE
SOAPdenovo-127mer going only to kmer of 63

### ISSUE THREAD

**Issue by opatty** [aquaskyline/SOAPdenovo2#28]
I am running SOAPdenovo2 v2.04-r214
When I run SOAPdenovo-127mer with a -K 67 it will not go over a kmer of
63.
Your guidance will be much appreciated
Cheers
Olivia

example of portions of output:

*********************
Pregraph
********************
Parameters: pregraph -s
../MK_SOAPdenovo.config -K 67 -R -o output/MK 
K should not be greater than
63.
In ../MK_SOAPdenovo.config, 1 lib(s), maximum read length 250, maximum
name length 256
................
********************
Map
*********************
Parameters: map -s ../MK_SOAPdenovo.config -g output/MK -K 67 
Kmer size:63.
Contig length cutoff: 65.

My run command is:
/home/tools/SOAPdenovo2/SOAPdenovo-127mer all -s ../MK_SOAPdenovo.config -o
output/MK -K 67 -R

My config file:
#MKconfig file
#maximal read length
max_rd_len=250
[LIB]
#average insert size
avg_ins=550
#if sequence needs to be reversed
reverse_seq=0
#in which part(s) the reads are used
asm_flags=3
#a pair of fastq file, read 1 file should always be followed by read 2 file
q1=/home/MK_R1_001.paired.fastq.gz
q2=/home/MK_R2_001.paired.fastq.gz

**Comment by phylobase-web** [comment]
opatty,

I had the same problem and fixed lines in Makefile.
The fix was committed, so get the latest release and rebuild to solve your
problem.

https://sourceforge.net/projects/soapdenovo2/files/SOAPdenovo2/

endo


2017-08-04 8:40 GMT+09:00 opatty <notifications@github.com>:

**Comment by opatty** [comment]
Fantastic! Thank you very much

**Comment by RootQJZ** [comment]
Hi endo,

I used the link you give with the latest release but have the same problem about SOAPdenovo-127mer command.

Any ideas about how can I fix this? Or how to fix lines in makefile to make kmer larger than 63 work?

Thanks!

**Comment by phylobase-web** [comment]
Hello RootQJZ.  Sorry for the delay of reply.

It seems something had changed...
The latest one is here:

https://github.com/aquaskyline/SOAPdenovo2

You should type

`git clone https://github.com/aquaskyline/SOAPdenovo2.git`

in your working directory.
