### ISSUE TITLE
how to choose the kmer number for the genome assembly.

### ISSUE THREAD

**Issue by fhu2008-tio** [aquaskyline/SOAPdenovo2#33]
Hi,
    when I run graphy and contig, different Kmer results differernt contig size, eg. kmer25=110M, kmer41=58M, does it normal?  which number of kmer should be choose for the following analysis???
   
     
my illunima date 350bp, PE150, 

example.config
max_rd_len=150
[LIB]
avg_ins=350
reverse_seq=0
asm_flags=1
rank=1
f1=/home/workplace/soapdenovo_350/cleanreads/350.1.fasta
f2=/home/workplace/soapdenovo_350/cleanreads/350.2.fasta

**Comment by cchd0001** [comment]
Hi  ,

The best K changed for different data .
You need to try more K and find the best.
Since you read is long enough ,feel free to try bigger K , like 83 or even bigger  . :-)

Hope this can help.
