### ISSUE TITLE
GapCloser max read size?

### ISSUE THREAD

**Issue by r1corre** [aquaskyline/SOAPdenovo2#34]
Dear developer. 
Gap-closer was initially developed to work with reads of a  maximum size of 150 nuc. 
How does GapCloser react with 2x300 nuc reads ?  
Does it use only the first 150 nuc or is the full information in the 300nuc  used for gap closing?
Thanks for your help 

Erwan

**Comment by aquaskyline** [comment]
GapCloser will truncate the reads to 150nt.
