### ISSUE TITLE
should have a real config.example

### ISSUE THREAD

**Issue by spikeliu** [aquaskyline/SOAPdenovo2#36]
I read the README file trying to learn how to prepare the "example.config" file, but there is no such a file anywhere. After several minutes, I finally found more details about it at the appendix part of README. For a regular user, you wouldn't expect them to be so smart to know "OK, as long as I keep reading, I will find the answer in the appendix part of README". So, I think it would be more user friendly to have a real example configuration file in the repository or at least say something about the "example.config" when it first appears in the README file. You know,  Add something in parentheses after "example.config" like "you can see the format of this example file in appendix A below" or "more details of example.config could be found in appendix A below".

**Comment by aquaskyline** [comment]
added example.config in the latest commit.
