### ISSUE TITLE
When reading in ".links" file, the first line with real data will be ignored. 

### ISSUE THREAD

**Issue by spikeliu** [aquaskyline/SOAPdenovo2#38]
https://github.com/aquaskyline/SOAPdenovo2/blob/8c5c44f9734cf8f85262bf6aaa1d596755d9fd42/standardPregraph/orderContig.c#L5793
https://github.com/aquaskyline/SOAPdenovo2/blob/8c5c44f9734cf8f85262bf6aaa1d596755d9fd42/standardPregraph/orderContig.c#L5827
I think the original purpose of code on line 5793 was to ignore the first line, which contains the label for each column in ".link" file (like what you did with ".readOnContig.gz" file). But in practice, it doesn't have such a line when it is generated by `outputLinks()`. As a result, on line 5827, when the file is parsed by `inputLinks()`, the first line with real data will be ignored.
The difference of number of records for ".links" file can also be detected by the stderr message ("new connections" after loading pair-end reads info and "Total PE links" when constructing scaffold) when using only one LIB. I hope I was wrong about the code, but could you please check the corresponding part to see if there is something wrong going on, I believe the problem is also in "fusion" part of the project.
Thanks.

**Comment by spikeliu** [comment]
Thank you for your reply. I recompiled the new branch, checked the log message in different function operations and the number of records in "links" file, the problem is gone.
Though I have never used the "fusion" program, but I check the logic of that part, it seems to me it will have the same problem as most code is copied instead of calling the functions from "standardgraph" directly, I think. So you might also want to add that line to the part too.
Thanks again~

**Comment by aquaskyline** [comment]
Also modified the fusion module. Thanks again for reporting the bug.
