### ISSUE TITLE
"make install" is not available anymore

### ISSUE THREAD

**Issue by hlfernandez** [aquaskyline/SOAPdenovo2#45]
Dear colleagues, it seems that the "make install" option is not available anymore, so maybe it would be a good idea to update the installation instructions in the main README.md (it says _'Then install executable to ${destination folder}/SOAPdenovo-V2.04/bin using "make install"'_). 

Thank you very much for this nice package. 

Regards,

Hugo.

**Comment by aquaskyline** [comment]
done.

**Comment by hlfernandez** [comment]
Thank you!
