### ISSUE TITLE
SOAPdenovo-fusion (command not found...)

### ISSUE THREAD

**Issue by ptsij** [aquaskyline/SOAPdenovo2#49]
Hi, I'm trying to use 'SOAPdenovo-fusion'.
Then I compile it using make on SOAPdenovo2-r241.
Other tools are working good: SOAPdenovo-63mer & SOAPdenovo-127mer
But, I couldn't use 'SOAPdenovo-fusion' and only got,

'bash: SOAPdenovo-fusion: command not found...' message.

I got the same error message after compiling with 'make debug=1'.
Can you please help me to solve this out?

**Comment by ptsij** [comment]
I just gave PATH to the all 3 packages and then, it worked !
SOAPdenovo-63mer and 127mer was executable since I installed them through bioconda but it was 2.40 version which doesn't hae -fusion.
Sorry for this, and I will just close this issue.

**Comment by franciscozorrilla** [comment]
would be nice to have the fusion module/command in the bioconda recipe :)

**Comment by Robvh-git** [comment]
I experienced the same issue. Indeed, setting PATH to the folder which contains all the 3 commands, fixes the problem.

**Comment by alephreish** [comment]
Please add SOAPdenovo-fusion to the conda recipe.
