### ISSUE TITLE
make err

### ISSUE THREAD

**Issue by seqyuan** [aquaskyline/SOAPdenovo2#52]
when I use the command 'make', some err like this:
`make`
pregraph_sparse_63mer.v1.0.3 cleaning done.                         
pregraph_sparse_63mer.v1.0.3 objects generated.                    
SOAPdenovo-63mer cleaning done.                              
In file included from arc.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc arc.c
In file included from attachPEinfo.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc attachPEinfo.c
In file included from bubble.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc bubble.c
In file included from compactEdge.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc compactEdge.c
In file included from concatenateEdge.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc concatenateEdge.c
In file included from connect.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc connect.c
In file included from contig.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc contig.c
In file included from cutTipPreGraph.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc cutTipPreGraph.c
In file included from cutTip_graph.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc cutTip_graph.c
In file included from kmer.c:26:                                
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
kmer.c:600: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc kmer.c
In file included from lib.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc lib.c
In file included from loadGraph.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc loadGraph.c
In file included from loadPath.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc loadPath.c
In file included from loadPreGraph.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc loadPreGraph.c
In file included from localAsm.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc localAsm.c
In file included from main.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc main.c
In file included from map.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc map.c
In file included from mem_manager.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc mem_manager.c
In file included from newhash.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
newhash.c: 在函数‘modular’中:
newhash.c:53: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
newhash.c:53: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
newhash.c:53: 错误：所在的函数内也只报告一次。)
newhash.c:53: 错误：expected ‘;’ before ‘temp’
newhash.c:54: 错误：‘temp’未声明(在此函数内第一次使用)
newhash.c: 在函数‘get_kmerset’中:
newhash.c:246: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
newhash.c:246: 错误：expected ‘;’ before ‘temp’
newhash.c:247: 错误：‘temp’未声明(在此函数内第一次使用)
newhash.c: 在函数‘search_kmerset’中:
newhash.c:288: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
newhash.c:288: 错误：expected ‘;’ before ‘temp’
newhash.c:289: 错误：‘temp’未声明(在此函数内第一次使用)
newhash.c: 在函数‘encap_kmerset’中:
newhash.c:400: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
newhash.c:400: 错误：expected ‘;’ before ‘temp’
newhash.c:422: 错误：‘temp’未声明(在此函数内第一次使用)
newhash.c: 在函数‘put_kmerset’中:
newhash.c:490: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
newhash.c:490: 错误：expected ‘;’ before ‘temp’
newhash.c:491: 错误：‘temp’未声明(在此函数内第一次使用)
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc newhash.c
In file included from node2edge.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc node2edge.c
In file included from orderContig.c:4:                         
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc orderContig.c
In file included from output_contig.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc output_contig.c
In file included from output_pregraph.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc output_pregraph.c
In file included from output_scaffold.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc output_scaffold.c
In file included from pregraph.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc pregraph.c
In file included from prlHashCtg.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc prlHashCtg.c
In file included from prlHashReads.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc prlHashReads.c
In file included from prlRead2Ctg.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc prlRead2Ctg.c
In file included from prlRead2path.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc prlRead2path.c
In file included from prlReadFillGap.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc prlReadFillGap.c
In file included from read2scaf.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc read2scaf.c
In file included from readInterval.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc readInterval.c
In file included from readseq1by1.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc readseq1by1.c
In file included from scaffold.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc scaffold.c
In file included from searchPath.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc searchPath.c
In file included from seq.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc seq.c
In file included from splitReps.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc splitReps.c
In file included from cutTip_graph2.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc cutTip_graph2.c
In file included from linearEdge.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc linearEdge.c
In file included from kmerhash.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
kmerhash.c: 在函数‘modular’中:
kmerhash.c:55: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
kmerhash.c:55: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
kmerhash.c:55: 错误：所在的函数内也只报告一次。)
kmerhash.c:55: 错误：expected ‘;’ before ‘temp’
kmerhash.c:56: 错误：‘temp’未声明(在此函数内第一次使用)
kmerhash.c: 在函数‘get_kmerset2’中:
kmerhash.c:217: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
kmerhash.c:217: 错误：expected ‘;’ before ‘temp’
kmerhash.c:218: 错误：‘temp’未声明(在此函数内第一次使用)
kmerhash.c: 在函数‘search_kmerset2’中:
kmerhash.c:268: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
kmerhash.c:268: 错误：expected ‘;’ before ‘temp’
kmerhash.c:269: 错误：‘temp’未声明(在此函数内第一次使用)
kmerhash.c: 在函数‘encap_kmerset2’中:
kmerhash.c:391: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
kmerhash.c:391: 错误：expected ‘;’ before ‘temp’
kmerhash.c:409: 错误：‘temp’未声明(在此函数内第一次使用)
kmerhash.c: 在函数‘put_kmerset2’中:
kmerhash.c:472: 错误：‘__uint128_t’未声明(在此函数内第一次使用)
kmerhash.c:472: 错误：expected ‘;’ before ‘temp’
kmerhash.c:473: 错误：‘temp’未声明(在此函数内第一次使用)
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc kmerhash.c
In file included from read2edge.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc read2edge.c
In file included from iterate.c:26:                        
inc/extfunc.h:215: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Kmer2int128’
Error in command: gcc -c -O3 -fomit-frame-pointer -w  -DMER63  -Iinc iterate.c
SOAPdenovo-63mer objects generated.                          
/usr/bin/ld: skipping incompatible ./standardPregraph/inc/libz.so when searching for -lz
/usr/bin/ld: skipping incompatible ./sparsePregraph/inc/libbam.a when searching for -lbam
/usr/bin/ld: skipping incompatible ./standardPregraph/inc/libbam.a when searching for -lbam
/usr/bin/ld: cannot find -lbam
collect2: ld 返回 1
make: *** [SOAPdenovo-63mer] 错误 

please help

**Comment by aquaskyline** [comment]
Please try using bioconda to install SOAPdenovo2.
