### ISSUE TITLE
Segmentation fault  during contig step

### ISSUE THREAD

**Issue by AllisonStander** [aquaskyline/SOAPdenovo2#53]
I am assembling a 2.5 Gbp plant genome (rooibos). The one run with a subset of my data, gave the following error:

**In error file:**
********************
Contig
********************

Parameters: contig -g SoapK53 -M 1 -R -s 00_SoapConfig -p 16 

Kmers sorted.
There is no vertex for kmer 0 c .
There is no vertex for kmer 0 30 .
/var/spool/gridengine/execd/grid05/job_scripts/7525145: line 16: 55940 Segmentation fault      
(core dumped)
 SOAPdenovo-63mer all -s 00_SoapConfig -K 53 -R -p 16 -o SoapK53 > SoapK53.log 2> SoapK53.err

I am new to bioinformatics, and would appreciate any help or input on how I can fix this.

Kind regards,
Allison

**Comment by aquaskyline** [comment]
There are probably some errors in the input or the configuration file.
