### ISSUE TITLE
standard pregraph bug when using large number of threads

### ISSUE THREAD

**Issue by travc** [aquaskyline/SOAPdenovo2#6]
I'm triggering an error (in `cutTipPreGraph.c` line 124).

> Start to remove frequency-one-kmer tips shorter than 82.
> Kmer 0 0 2d199 b575fb763403b451 is not found, node1 0 0 34666 d5d7edd8d00ed145 .

The bug occurs when in the standard pregraph step with `-p 30`, but does not occur when I use `-p 8`... So it feels like a mutex (or lack thereof) bug in one of the data-structures.

The assembly I'm attempting is a simple test.  The single library I'm using only covers the ~270 Mbase genome to a median depth of about 25, which might be relevant.

I don't have a minimal test-case I can send, though I could give you access to the input files (~13.5GB) if needed.

Full stderr output:
```
Version 2.04: released on July 13th, 2012
Compile Sep 25 2015     11:07:28

********************
Pregraph
********************

Parameters: pregraph -s test.cfg -K 41 -p 30 -R -o test_K41 

In test.cfg, 1 lib(s), maximum read length 600, maximum name length 256.

30 thread(s) initialized.
Import reads from file:
 /data/archive/YL-GF-02/trimmed/2011WAN043/trim_pe1.fastq.gz
Import reads from file:
 /data/archive/YL-GF-02/trimmed/2011WAN043/trim_pe2.fastq.gz
Import reads from file:
 /data/archive/YL-GF-02/trimmed/2011WAN043/trim_sing1.fastq.gz
Import reads from file:
 /data/archive/YL-GF-02/trimmed/2011WAN043/trim_sing2.fastq.gz
Time spent on hashing reads: 676s, 89689873 read(s) processed.
LIB(s) information:
 [LIB] 0, avg_ins 317, reverse 0.
854464360 node(s) allocated, 5137311711 kmer(s) in reads, 5137311711 kmer(s) processed.
done hashing nodes
828819958 linear node(s) marked.
Time spent on marking linear nodes: 15s.
Time spent on pre-graph construction: 691s.

Start to remove frequency-one-kmer tips shorter than 82.
Kmer 0 0 2d199 b575fb763403b451 is not found, node1 0 0 34666 d5d7edd8d00ed145 .
```

**Comment by aquaskyline** [comment]
Travc, will the problem persist when using another large number of threads beside 30, say 29 or 31?

**Comment by travc** [comment]
I haven't tested it extensively, but `-p 31` pregraph does work.  If it is the sort of error I think it is, that is not surprising.  It might also be difficult to reproduce on a different system.  As I said, probably a shared data-structure which isn't getting locked when it should be.

pinching bubbles is failing (very repeatably) with both standard and sparse pregraphs for this data, so maybe there is a problem with the pregraphs even when that step does run to completion (or it could be unrelated).  I'll make a a new issue for that.
