### ISSUE TITLE
incompatible libbam.a

### ISSUE THREAD

**Issue by xqhuang1018** [aquaskyline/SOAPdenovo2#61]
Hi, when "make" the SOAPdenovo2 on the Power8 (ppc64le), it is not able to generate the executables, because of the preexisted libbam.a can not be linked properly.
Here is the error message:
/usr/bin/ld: skipping incompatible ./sparsePregraph/inc/libbam.a when searching for -lbam
/usr/bin/ld: skipping incompatible ./standardPregraph/inc/libbam.a when searching for -lbam
/usr/bin/ld: cannot find -lbam
collect2: error: ld returned 1 exit status
make: *** [SOAPdenovo-63mer] Error 1

the libraries (libbam.a libbam_1.a ) are already included in the deposit. Please provide a way to figure this issue out.

**Comment by phylobase-web** [comment]
The error message tells the library is incompatible.  You should remove libbam.a and libbam_1.a so that `make' tool can rebuild them properly.
