### ISSUE TITLE
reading too few reads? Not supporting gz format?!

### ISSUE THREAD

**Issue by bitcometz** [aquaskyline/SOAPdenovo2#63]
Hello,
I try to run SOAPdenovo with around 10g data, however, It seems cannot properly reads the raw reads:

********************
Pregraph
********************

Parameters: pregraph -s config_file -d 1 -p 24 -K 37 -R -o s_1 

In config_file, 1 lib(s), maximum read length 150, maximum name length 256.

24 thread(s) initialized.
Import reads from file:
 path/s_1_HHMYJDSXX_L3_1.fq.gz
Import reads from file:
 path/s_1_HHMYJDSXX_L3_2.fq.gz
Time spent on hashing reads: 1s, 356 read(s) processed.
LIB(s) information:
 [LIB] 0, avg_ins 350, reverse 0.
37344 node(s) allocated, 39516 kmer(s) in reads, 39516 kmer(s) processed.
done hashing nodes
35172 kmer(s) removed.
Time spent on delowcvgNode: 0s.
2098 linear node(s) marked.
Time spent on marking linear nodes: 0s.
Time spent on pre-graph construction: 1s.

Does it not support the gz format? **I try to unzip the fq and it works well again.**

Thanks!

**Comment by aquaskyline** [comment]
mostly likely due to a version problem of the gzip library you are linking to.

**Comment by NiuNiuguohao** [comment]
I met the same problem. Could you please tell me how did you fix it? Thanks!

**Comment by HZAU-Wss** [comment]
I had the same problem. 2 gigabytes of clean date  can be run with ”spades“, but “soap” can only read 20,000 reads.

**Comment by victorzhu30** [comment]
Do you know how to solve it? I met same problem 
https://github.com/aquaskyline/SOAPdenovo2/issues/63#issuecomment-1997456227
