### ISSUE TITLE
segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by bioramg** [aquaskyline/SOAPdenovo2#67]
Hi,
I would like to assemble the plant mitochondrial genome using Illumina pair reads. So, I created the configuration file as follows:

#maximal read length
max_rd_len=150
[LIB]
#average insert size of the library
avg_ins=300
#if sequences are forward-reverse of reverse-forward
reverse_seq=0
#in which part(s) the reads are used
asm_flags=3
#in which order the reads are used while scaffolding
rank=1
#cutoff of pair number for a reliable connection (at least 3 for short insert size)
pair_num_cutoff=3
#minimum aligned length to contigs for a reliable read location (at least 32 for short insert size)
map_len=32
#a pair of fastq file, read 1 file should always be followed by read 2 file
f1=/home/pmslab/Desktop/filtered_1_paired.fq
f2=/home/pmslab/Desktop/filtered_2_paired.fq

I have given the following command to execute:
./SOAPdenovo-127mer all -K 67 -p 8 -s config.txt -o ./assembly/127kmer

But, I am getting an error. What could be the problem? could you please suggest to me?

Version 2.04: released on July 13th, 2012
Compile Jul  9 2013     11:57:30

********************
Pregraph
********************

Parameters: pregraph -s config.txt -K 67 -p 8 -o ./assembly/127kmer

In config.txt, 1 lib(s), maximum read length 150, maximum name length 256.

8 thread(s) initialized.
Import reads from file:
 /home/pmslab/Desktop/filtered_1_paired.fq
Import reads from file:
 /home/pmslab/Desktop/filtered_2_paired.fq
zsh: segmentation fault (core dumped)  ./SOAPdenovo-127mer all -K 67 -p 8 -s config.txt -o ./assembly/127kmer

Thank you.

**Comment by haleyhallowell** [comment]
Hi! I had a similar problem running the program on a SLURM. It turns out my input file was incorrectly formatted. Segmentation errors are often due to two things: 1. too little memory was allocated to the run (most common) or 2. the file is corrupted. If you have the option, I would give it an insane amount of RAM and see if that fixes the issue. If not, i'd check your input file and make sure its in the correct .fq format.

**Comment by liuruia** [comment]
f1=/home/pmslab/Desktop/filtered_1_paired.fq
f2=/home/pmslab/Desktop/filtered_2_paired.fq

Try this：
q1=/home/pmslab/Desktop/filtered_1_paired.fq
q2=/home/pmslab/Desktop/filtered_2_paired.fq
