### ISSUE TITLE
Small N50 due to read length cutoff

### ISSUE THREAD

**Issue by shanewidanagama** [aquaskyline/SOAPdenovo2#70]
Hello, I am attempting to complete a de novo genome assembly of an angiosperm genome, and I am struggling to determine the correct configuration for my assembly. In particular, I am having trouble determining an appropriate rd_ln_cutoff.

Initially, a rd_ln_cutoff of 100 produced an assembly with a 30% gap percentage. A second attempt with 150 rd_ln_cutoff had less than 1% gap percentage but a contig N50 of  only 150 bp and no scaffolds longer than 50K bp. A third attempt with a 125 rd_ln_cutoff slightly improved contig N50 to 878, had a <1% gap percentage, and 2.15% of the scaffolds were longer than 50Kb. How do I determine an appropriate read length cutoff?

The Illumina reads I used are paired end, trimmed, and made of up three libraries. The genome is estimated to be 750Gb long.

These are the average read lengths and standard deviations of each library:
```
[shane88@gra-login1 raw_data]$ cat Sample_stats_3.txt
total 289519092 avg=137.047316 stddev=539.888658
[shane88@gra-login1 raw_data]$ cat Sample_stats_5.txt
total 335632386 avg=145.728888 stddev=184.019201
[shane88@gra-login1 raw_data]$ cat Sample_stats_6.txt
total 329998742 avg=145.161650 stddev=221.256105
```

In addition, this is my current config file:
```
#maximal read length
max_rd_len=150
[LIB]
#average insert size of the library
avg_ins=300
#if sequences are forward-reverse of reverse-forward
reverse_seq=0
#in which part(s) the reads are used (only contigs, only scaffolds, both contigs and scaffolds, only gap closure)
asm_flags=3
#cut the reads to the given length
rd_len_cutoff=125
#in which order the reads are used while scaffolding
rank=1
# cutoff of pair number for a reliable connection (at least 3 for short insert size)
pair_num_cutoff=3
#minimum aligned length to contigs for a reliable read location (at least 32 for short insert size)
map_len=32
#paired-end fastq files, read 1 file should always be followed by read 2 file
q1=SRR7881463_1P.fastq
q2=SRR7881463_2P.fastq
#paired-end fastq files, read 1 file should always be followed by read 2 file
q1=SRR7881465_1P.fastq
q2=SRR7881465_2P.fastq
#paired-end fastq files, read 1 file should always be followed by read 2 file
q1=SRR7881466_1P.fastq
q2=SRR7881466_2P.fastq
```
All three libraries are inputted as one library due to their similar average read lengths. Do you think inputting each
library separately could improve my assembly? Are there any other parameters in my config file that you think could improve results?

**Comment by aquaskyline** [comment]
you configuration file looks good. but to tell what are the best parameters, you will have to try out a few.

**Comment by skylar1997** [comment]
Hello, I am a person who just started to learn, and I would like to ask how to solve the following error after compiling?

pregraph_sparse_63mer.v1.0.3 cleaning done.                         
/bin/sh: g++: 未找到命令p...                               
Error in command: g++ -c -O3 -fomit-frame-pointer -w -D_63MER_ -m64  -I./inc build_graph.cpp
/bin/sh: g++: 未找到命令...                               
Error in command: g++ -c -O3 -fomit-frame-pointer -w -D_63MER_ -m64  -I./inc build_edge.cpp
/bin/sh: g++: 未找到命令cpp...                               
Error in command: g++ -c -O3 -fomit-frame-pointer -w -D_63MER_ -m64  -I./inc multi_threads.cpp
/bin/sh: g++: 未找到命令pp...                               
Error in command: g++ -c -O3 -fomit-frame-pointer -w -D_63MER_ -m64  -I./inc build_preArc.cpp
/bin/sh: g++: 未找到命令e.cpp...                               
Error in command: g++ -c -O3 -fomit-frame-pointer -w -D_63MER_ -m64  -I./inc pregraph_sparse.cpp
/bin/sh: g++: 未找到命令                               
Error in command: g++ -c -O3 -fomit-frame-pointer -w -D_63MER_ -m64  -I./inc io_func.cpp
/bin/sh: g++: 未找到命令                              
Error in command: g++ -c -O3 -fomit-frame-pointer -w -D_63MER_ -m64  -I./inc global.cpp
/bin/sh: g++: 未找到命令novo.cpp...                               
Error in command: g++ -c -O3 -fomit-frame-pointer -w -D_63MER_ -m64  -I./inc convert_soapdenovo.cpp
pregraph_sparse_63mer.v1.0.3 objects generated.                    
SOAPdenovo-63mer cleaning done.                              
SOAPdenovo-63mer objects generated.                                
/bin/sh: g++: 未找到命令
make: *** [SOAPdenovo-63mer] 错误 127
