### ISSUE TITLE
About the err.txt

### ISSUE THREAD

**Issue by Otis-chan** [aquaskyline/SOAPdenovo2#73]
Hi,
I've met a problem, which makes me a little bit confused.
I wrote a script, 1.0_SOAP_pregraph.sh: 
`SOAPdenovo-63mer sparse_pregraph \
-s /home/chphl/02_SOAP_assembly/genome.config \
-K 21 \
-g 15 \
-z 320000000 \
-d 1 \
-e 1 \
-R \
-r 0 \
-p 20 \
-o /home/chphl/02_SOAP_assembly/21merout`
And I use the `./1.0_SOAP_pregraph.sh 1>pregraph.log 2>pregraph.err &` to run the assembler. I found that there is nothing in the log, but there are some information in the err:
`********************
SparsePregraph
********************`
`Parameters: pregraph_sparse -s /home/chphl/02_SOAP_assembly/ts_genome.config -K 21 -g 15 -z 320000000 -d 1 -e 1 -R  -r 0 -p 20 -o /home/chphl/02_SOAP_assembly/21merout
Start to build the sparse de Brujin graph, round: 1
1 io thread initialized.
Import reads from file:
 /home/chphl/01_clean_ts_data/ts_clean_1.fastq.gz
20 work threads initialized.`
Then I top, the assembler is still running. Did I use the wrong command or something?

**Comment by cchd0001** [comment]
Hi ,

Construct the DBG could be an computational intensive step especially when your input fastq file are big enough.
Plus, The sparse_pregraph use less momery then normally pregraph but need more time because it has two round of loading files and choping reads into kmers.

**Comment by Otis-chan** [comment]
thank you!
