### ISSUE TITLE
Empty fastq input results in infinite "air_return error" loop

### ISSUE THREAD

**Issue by magcurly** [aquaskyline/SOAPdenovo2#75]
Dear Developers,

I found that an empty fastq file as input of SOAPdenovo2 will leads to an infinite loop which keeps reporting"Error: aio_return error". Therefore, I found changing line 807 of "prlHashReads.c" by adding "return 0;" would be able to stop the loop.

I am not a C# user, so I don't know whether is correct to do this. If you found it useful, please check the codes.

Yours Sincerely,
Jiahui

**Comment by cchd0001** [comment]
Thanks for this important bug report. I have add exit(-1） at line 607 of prlHashReads.c to exit the program when aio_error happened.
