### ISSUE TITLE
operation

### ISSUE THREAD

**Issue by BAOjinbo** [aquaskyline/SOAPdenovo2#76]
Why prompt ：terminated  ./SOAPdenovo-127mer all -s config_file -k 127-R -o output_a > ass.log 2>

**Comment by cchd0001** [comment]
Could you please provide more details ?

**Comment by BAOjinbo** [comment]
I tried again
![DD3518A4-943E-43D0-9029-753CAFE83BF5](https://user-images.githubusercontent.com/78304967/115243970-0ea6bd80-a156-11eb-92c2-6cf7bb090cf3.png)

Here is my config_file
![CA1A0B0E-A39F-4C55-9574-96D3F2B11585](https://user-images.githubusercontent.com/78304967/115243389-76103d80-a155-11eb-911a-ec0844342fe4.png)

And this is my data position 
![FCE9F223-AF5A-495F-B1E4-3DBCA6A79EC1](https://user-images.githubusercontent.com/78304967/115243825-e6b75a00-a155-11eb-8290-11d97138faa2.png)

I can't figure out what the problem is

**Comment by cchd0001** [comment]
Could you please provide the content of ass.log and ass.err ?

**Comment by BAOjinbo** [comment]
This is ass. log     nothing
![A7682C2D-071F-4013-B658-0A6129007E71](https://user-images.githubusercontent.com/78304967/115258646-c098b680-a163-11eb-8a42-5d14bb7bbbf5.png)

This is ass.err 
![827174AA-3517-4598-AD6B-AB74DE693367](https://user-images.githubusercontent.com/78304967/115258709-d0b09600-a163-11eb-9702-c744bbc153df.png)

**Comment by cchd0001** [comment]
Everything looks OK to me. Please check your read length ( need greater than 127 since you choose K=127 ).

**Comment by BAOjinbo** [comment]
Ok. I will try it. Thank you so much.&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Lidong ***@***.***&gt;
Date: Tue,Apr 20,2021 8:09 AM
To: aquaskyline/SOAPdenovo2 ***@***.***&gt;
Cc: BAOjinbo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [aquaskyline/SOAPdenovo2] operation (#76)





 
Everything looks OK to me. Please check your read length ( need greater than 127 since you choose K=127 ).
