### ISSUE TITLE
not resolved gaps of 1 nucleotide

### ISSUE THREAD

**Issue by glopatriello** [aquaskyline/SOAPdenovo2#80]
Hi there!

I've performed gapclosing on my transcriptome assembly using GapCloser with Illumina data. I've observed that after gapclosing , I have many unresolved gaps of 1 nucleotide in my transcriptome assembly. Remapping the reads against the assembly after gapclosing, I've observed that the reads spans the gaps but in proximity of the gaps some mismatches or indels are present in the mapping reads. 

I was wondering if the software considers these gaps as not resolved due the presence of differences in the mapping reads in these regions.

Best,
Giulia

**Comment by cchd0001** [comment]
Hi Giulia

Change the ```gapCount``` to ```contigCount```  in ContigAssemblerForFill.hpp:491  will solve this problem.

Best wishes 
Lidong Guo
