### ISSUE TITLE
how to use multi-kmer option: setting kmer step size and minimum k-mer size

### ISSUE THREAD

**Issue by jvollme** [aquaskyline/SOAPdenovo2#9]
Hello, 
Your publication states that SOAPdenovo2 implements a multi-kmer strategy similar to IBDA_UD and megahit. But how exactly can it be used?

The instructions state that the "-m" argument sets the maximum k-mer size. But how exactly are the **minimum** k-mer size and the step-size set?
 
Is the minimum k-mer size simply set with the "-K" argument? Are multi-kmers used automatically if both "-K" __and__ "-m" are set?

The pseudocode in the supplemental data of the SOAPdenovo2-paper seems to indicate a hard-coded step size of 1. Is this true? Wouldn't that restrict the usage to very small k-mer ranges? Or can the step-size be customized?

thanks,
john

**Comment by aquaskyline** [comment]
Please use MEGAHIT for a matured multi-kmer implementation.
